### ISSUE TITLE
Migration fails at task['uuid'] = re.search(UUID_REGEX, stdout).group(0)

### ISSUE THREAD

**Issue by orsenthil** [matt-snider/todoist-taskwarrior#4] opened 2021-10-12 14:36 UTC
Do you recognize the reason for this error?

> $ task --version
2.5.3

```
Task 2 of 135: * **Bugs**
tid: 3443278955
name: * **Bugs**
project: Bag
priority:
tags:
entry: 2019-10-10T13:13:01+00:00
due:
recur:

Import this task? (y, n, d, t, P, p, r, q, ?): y
Importing '* **Bugs**' (Bag)... FAILED ('NoneType' object has no attribute 'group')
Traceback (most recent call last):
  File "/Users/senthilx/cpython-3.11/lib/python3.11/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/senthilx/cpython-3.11/lib/python3.11/runpy.py", line 86, in _run_code
    exec(code, run_globals)
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/senthilx/git/todist-taskwarrior2/todoist_taskwarrior/cli.py", line 372, in <module>
    cli()
    ^^^^^
  File "/Users/senthilx/venvs/cpython/lib/python3.11/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/senthilx/venvs/cpython/lib/python3.11/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/senthilx/venvs/cpython/lib/python3.11/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/senthilx/venvs/cpython/lib/python3.11/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/senthilx/venvs/cpython/lib/python3.11/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/senthilx/venvs/cpython/lib/python3.11/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/senthilx/git/todist-taskwarrior2/todoist_taskwarrior/cli.py", line 215, in migrate
    add_task_interactive(**data)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/senthilx/git/todist-taskwarrior2/todoist_taskwarrior/cli.py", line 339, in add_task_interactive
    return add_task(**task_data)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/senthilx/git/todist-taskwarrior2/todoist_taskwarrior/cli.py", line 230, in add_task
    return taskwarrior.task_add(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/senthilx/venvs/cpython/lib/python3.11/site-packages/taskw/warrior.py", line 693, in task_add
    task['uuid'] = re.search(UUID_REGEX, stdout).group(0)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by matt-snider** [comment] 2021-10-15 11:13
Hey @orsenthil 

This originates from the [taskw](https://github.com/ralphbean/taskw) library and there appear to be two recent issues that relate to it: [#144](https://github.com/ralphbean/taskw/issues/144) and [#146](https://github.com/ralphbean/taskw/issues/146).

What happens here, is that the taskw library reads stdout and tries to parse out the uuid that the `task` cli generated. For whatever reason the uuid is not present in the output. 

I think this is specific to taskwarrior 2.5.3 and was fixed in fixed in pull [147](https://github.com/ralphbean/taskw/pull/147), but there hasn't been a release of taskw since then. 

I have two ideas on how this might be fixed:

(1) The easiest for you would be to add `verbose=new-uuid` in your taskrc

(2) Otherwise, you can try to change the requirements.txt to point to the unreleased version and then install and re-run. But of course, as an unreleased version, it might still have bugs/regressions.

```diff
- # Temporarily use this until upstream PR #121 is merged
- # https://github.com/ralphbean/taskw/pull/121 
- git+git://github.com/matt-snider/taskw.git@develop
+ git+git://github.com/ralphbean/taskw.git@develop
```

Let me know if you have some time to try that out

**Comment by orsenthil** [comment] 2021-10-16 01:44
Hi @matt-snider , both these suggestions worked. I think, applying the patch to your repo will be good idea.

--- 
Non interactive migrate failed for me at 85th task. It might probably be a local task issue or API rate.  

For the problem in the issue, your solution works. Thank you.

**Comment by matt-snider** [comment] 2021-10-21 13:48
@orsenthil Thank you for testing that out and providing feedback. Do you want me to help you figure out the problem in the 85th task?

**Closed as completed** 2024-06-27 10:04 UTC
